### ISSUE TITLE
ReaderOptions.MessageChannel is ignored

### ISSUE THREAD

**Issue by cornelk** [apache/pulsar-client-go#211]
#### Expected behavior

Reader uses the `ReaderOptions.MessageChannel` channel to send messages.

#### Actual behavior

Reader never sends to that channel if set.

#### Steps to reproduce

Search for code references to `ReaderOptions.MessageChannel`.

**Comment by bithavoc** [comment]
Heads up that when this gets implemented and users set `MessageChannel`, it should not start streaming immediately upon `CreateReader` because users may want to do `SeekByTime` first before wanting to receive messages via the channel, so we could provide an additional method `StartStreaming` or something that actually starts the goroutine and feeds `MessageChannel`, otherwise the channel may start receiving messages based on `MessageID` (earliest or latest) before having the change to call `SeekByTime`.

**Comment by merlimat** [comment]
Closing issue as this was fixed long time ago.
