### ISSUE TITLE
Question about Connection Pool Close() function implementation

### ISSUE THREAD

**Issue by tech4gk** [apache/pulsar-client-go#614]
Question refers to the implementation of [connection_pool.go](https://github.com/apache/pulsar-client-go/blob/master/pulsar/internal/connection_pool.go)

Expected Behavior:
Based on a typical connection pool implementation, since there is no release method, When client calls the Close() method, the expectation is to release the connection to the connection pool. 
Actual Behavior:
Client deletes the connection from the connection pool and it closes the connection, which as per code, "Close closes the connection by closing underlying socket connection and closeCh. This also triggers callbacks to the ConnectionClosed listeners."

The side effect of this is, when the producer code, defers the close connection call, when the function goes out of scope, it closes the underlying connection too. This can cause performance issues, if the connection gets constructed and destroyed with in the same func. (as per the example code)

Similar question around the producer implementation too as found in [producer.go](https://github.com/apache/pulsar-client-go/blob/master/pulsar/producer.go)

Suggestion:
1. Need better documentation on how connection pool works.
2. Based on the sample code provided on example's [producer.go](https://github.com/apache/pulsar-client-go/blob/master/examples/producer/producer.go), to avoid client connection creation and destruction.  is the following recommended 
 a. Create the client once when the client app initialize, with the MaxConnectionsPerBroker setting  to a preferred configuration 
 b. Create the producer or consumer once when the client app initializes
 c.  Call the close method on producer when the client app shuts down
 d.   Call the close method on Client when the client app shuts down

If the above sounds like a good approach, can we please have the example code fixed, to reflect this change as it can set a better model for the developers.

**Comment by merlimat** [comment]
@tech4gk A single `Connection` object (and its underlying TCP socket) can be shared across multiple producers and consumers.

When a producer/consumer gets closed, that won't affect the status of the `Connection`. Rather, when the connection gets closed (eg: in reaction of the underlying TCP socket being closed), it's correct to get it out of the pool, because at that point it cannot be reused anymore.

> a. Create the client once when the client app initialize, with the MaxConnectionsPerBroker setting to a preferred configuration

Yes, the application is expected to create a single Client instance throughout its lifecycle

> b. Create the producer or consumer once when the client app initializes

There are many different approaches there. For example you could create a producer at the first time you're going to use it. After that, the producer instance is designed to be "long-lived", and be used to published many messages.

>  Call the close method on producer when the client app shuts down

Yes, or when the producer is not going to be needed anymore

> Call the close method on Client when the client app shuts down

Yes

**Comment by tech4gk** [comment]
Highly appreciated. Thanks a lot for the clarification @merlimat
